<?php

namespace CmsBundle\Repository;

use Doctrine\ORM\QueryBuilder;

/**
 * SlideRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends AbstractPostRepository
{
    public function findMany($criterias = array(), $orders = array(), $numbers = array(), $options = array())
    {
        /** @var QueryBuilder $qb */
        $qb = parent::findMany($criterias, $orders, $numbers, $options);

        if(isset($criterias['sliderUniqueSlug'])) {
            $qb->leftJoin('o.collection', 'collection')->addSelect('collection');
            $qb->andWhere('collection.uniqueSlug = :sliderUniqueSlug')->setParameter('sliderUniqueSlug', $criterias['sliderUniqueSlug']);
        }

        $qb->leftJoin('o.cover', 'cover')->addSelect('cover');
        $qb->leftJoin('o.background', 'background')->addSelect('background');

        return $qb;
    }


}
