<?php

namespace CmsBundle\Repository;

/**
 * LayoutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LayoutRepository extends \Doctrine\ORM\EntityRepository
{
}
