<?php

namespace CmsBundle\Repository;

use Doctrine\ORM\QueryBuilder;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends BaseRepository
{
    /**
     * @param array $criterias
     * @param array $orders
     * @param array $numbers
     * @param array $options
     * @return QueryBuilder
     */
    public function findMany($criterias = array(), $orders = array(), $numbers = array(), $options = array())
    {
        $qb = $this->createQueryBuilder('page');

        return $qb;
    }

    /**
     * @param array $criterias
     * @param array $options
     * @return QueryBuilder
     */
    public function findOne($criterias = array(), $options = array())
    {
        $qb =
            $this->createQueryBuilder('page')
                ->leftJoin('page.folder', 'folder')->addSelect('folder')
                ->leftJoin('folder.translations', 'folderTranslations')->addSelect('folderTranslations')
                ->leftJoin('page.layout', 'layout')->addSelect('layout')
                ->leftJoin('page.translations', 'translations')->addSelect('translations');


        if (isset($criterias['id'])) {
            $qb->andWhere('page.id = :id')->setParameter('id', $criterias['id']);
        } else {
            $qb->andWhere('page.slug = :slug')->setParameter('slug', $criterias['slug']);
        }


        if (isset($options['admin']) and !$options['admin']) {
            $qb->andWhere('page.published = :published')->setParameter('published', true);
            $qb->andWhere('page.publishedStart < :publishedStart')->setParameter('publishedStart', new \DateTime('now'));
        }

        if (isset($criterias['folder']) and $criterias['folder'] != null) {
            $qb->andWhere('folder.slug = :folder')->setParameter('folder', $criterias['folder']);
        }

        return $qb;
    }
}
