<?php

namespace CmsBundle\Repository;

/**
 * ArticleTagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends AbstractTaxonomyRepository
{

}
