<?php

namespace App\Repository;
use App\Entity\Dose;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;
/**
 * DoseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DoseRepository extends ServiceEntityRepository
{
	
	// L'argument $registry est automatiquement injecté par Symfony
    public function __construct(ManagerRegistry $registry)
    {
        // ⚠️ Appelez le constructeur parent avec le ManagerRegistry et la classe d'entité
        parent::__construct($registry, Dose::class); 
    }

	public function getdetaildose($dose){
		$qb = $this->createQueryBuilder('d');
		$qb->innerJoin('d.detail_dose', 'dd')
		->where('d IN (:ds)')
		->setParameter('ds', $dose);
			
		return $qb->getQuery()->getResult();
	}

	public function findDistinctProtocolsByModalite(string $modalite): array
    {
        return $this->createQueryBuilder('d')
            // 1. Sélectionne uniquement la valeur distincte du champ 'protocole'
            ->select('DISTINCT d.protocole')
            

            // 2. Ajoute la condition de filtrage sur le champ 'modalite'
            ->where('d.modalite = :modalite')
            
            // 3. Assigne la valeur du paramètre pour éviter les injections SQL
            ->setParameter('modalite', $modalite)
            
            // 4. Exécute la requête
            ->getQuery()
            ->getSingleColumnResult();
    }

	/**
     * Retourne la liste des protocoles distincts.
     *
     * @return array<string>
     */
    public function findDistinctProtocols(): array
    {
        return $this->createQueryBuilder('d')
            // Sélectionne uniquement la valeur distincte du champ 'protocole'
            ->select('DISTINCT d.protocole as name')
            // Exécute la requête et récupère le résultat sous forme d'un tableau de tableaux
            ->getQuery()
            ->getResult(); // Récupère le résultat sous forme d'un tableau simple (e.g., ['Protocole A', 'Protocole B', ...])
    }

	public function findDistinctProtocolsByModalites(array $modalites): array
    {
        // 1. Gérer le cas où la liste est vide pour éviter une erreur SQL
        if (empty($modalites)) {
            return $this->findDistinctProtocols();
        }

        return $this->createQueryBuilder('d')
            // Sélectionne uniquement la valeur distincte du champ 'protocole'
            ->select('DISTINCT d.protocole as name')
            
            // 2. Utilisation de l'opérateur IN
            // Cherche les doses dont la modalité est DANS la liste fournie.
            ->where('d.modalite IN (:modalites)')
            
            // 3. Assigne la valeur du paramètre
            ->setParameter('modalites', $modalites)
            
            // 4. Exécute la requête
            ->getQuery()
            ->getResult();
    }
}
