<?php

namespace AppBundle\Repository;

/**
 * BodypartsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BodypartsRepository extends \Doctrine\ORM\EntityRepository
{
}
