<?php

namespace AppBundle\Repository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends \Doctrine\ORM\EntityRepository
{
    public function getalleicatgorie(){
        $qb = $this->createQueryBuilder('c');
        $qb->where('c.codeCategorie != :codeser')
        ->setParameter('codeser','01');
        return $qb->getQuery()->getResult();        
    }
}
