<?php

namespace AppBundle\Repository;

/**
 * ConversionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConversionRepository extends \Doctrine\ORM\EntityRepository
{
	
	public function findByFacteur($unite){
		$qb = $this->createQueryBuilder('c')
		->where('c.unitesource = :unite')
		->setParameter('unite',$unite);
		return $qb->getQuery()->getResult();
		
		if($qb->getQuery()->getResult() and count($qb->getQuery()->getResult())>0)
		return ["valeur" => $qb->getQuery()->getResult()[0]->getFacteur()*$valeur, "unite" =>$qb->getQuery()->getResult()[0]->getUnitecible()];
	}
	

}
