<?php

namespace AppBundle\Repository;

/**
 * ConversionAgePoidsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConversionAgePoidsRepository extends \Doctrine\ORM\EntityRepository
{
	
	
	
}
