<?php

namespace AppBundle\Repository;

/**
 * CritereEsrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CritereEsrRepository extends \Doctrine\ORM\EntityRepository
{
}
