<?php

namespace AppBundle\Repository;

/**
 * detail_doseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class detail_doseRepository extends \Doctrine\ORM\EntityRepository
{
	
    
    
    public function getdetaildose($dose){
		$qb = $this->createQueryBuilder('dd')	
		->where('dd.dose IN (:ds)')
		->setParameter('ds', $dose);			
		return $qb->getQuery()->getResult();
	}

	
	public function getdetaildoseall(){
		$qb = $this->createQueryBuilder('dd');
		$qb->select('dd.protocole');
		$qb->distinct();
		return $qb->getQuery()->getResult();
	}

	
	public function getprotocolescanner(){
		$qb = $this->createQueryBuilder('dd');
		$qb->select('dd.protocole');
		$qb->where('dd.modalite IN (:modalite)');
		$qb->andWhere('dd.unite IN (:unite)');
		$qb->setParameter('modalite','SR')
		->setParameter('unite','mGy.cm');
		$qb->distinct();
		return $qb->getQuery()->getResult();
	}
	
	
	public function getprotocolemamo(){
		$qb = $this->createQueryBuilder('dd');
		$qb->select('dd.protocole');
		$qb->where('dd.modalite IN (:modalite)');
		$qb->setParameter('modalite','MG');
		$qb->distinct();
		return $qb->getQuery()->getResult();
	}
	
	public function getprotocoleradio(){
		$qb = $this->createQueryBuilder('dd');
		$qb->select('dd.protocole');
		$qb->where('dd.modalite IN (:modalite)');
		$qb->andWhere('dd.unite like :unite');
		$qb->setParameter('modalite','SR')
		->setParameter('unite','%2%');
		$qb->distinct();
		return $qb->getQuery()->getResult();
	}
	
	
	public function getprotocolescannerall(){
		$qb = $this->createQueryBuilder('dd');
		$qb->select('dd');
		$qb->where('dd.modalite IN (:modalite)');
		$qb->andWhere('dd.unite IN (:unite)');
		$qb->setParameter('modalite','SR')
		->setParameter('unite','mGy.cm');

		return $qb->getQuery()->getResult();
	}
	
	
	public function getprotocolemamoall(){
		$qb = $this->createQueryBuilder('dd');
		$qb->select('dd');
		$qb->where('dd.modalite IN (:modalite)');
		$qb->setParameter('modalite','MG');
		
		return $qb->getQuery()->getResult();
	}
	
	public function getprotocoleradioall(){
		$qb = $this->createQueryBuilder('dd');
		$qb->select('dd');
		$qb->where('dd.modalite IN (:modalite)');
		$qb->andWhere('dd.unite like :unite');
		$qb->setParameter('modalite','SR')
		->setParameter('unite','%2%');
		
		return $qb->getQuery()->getResult();
	}
	
	public function getprotocoleall(){

		$qb = $this->createQueryBuilder('dd');
		$qb->select('dd.protocole');				
		$qb->distinct();
		return $qb->getQuery()->getResult();
	}
	

	public function getdetaildosewhitoutEntireBody($dose){
		$qb = $this->createQueryBuilder('dd')
		->where('dd.dose IN (:ds)')
		->andWhere('dd.bodyPart <> :entirebody ')
		->setParameter('ds', $dose)
		->setParameter('entirebody','Entire body');
		return $qb->getQuery()->getResult();
	}
	
	public function searchdetaildoses($criteres){
		
		$resultats=[];
		foreach ($criteres as $critere){
			$qb = $this->createQueryBuilder('dd');
			$resultat=$qb->where('dd.valeur like :ds1')
			->orWhere('dd.xrayTubeContent like :ds2')
			->orWhere('dd.bodyPartEasydose like :ds3')
			->orWhere('dd.kvp like :ds4')
			->orWhere('dd.unite like :ds5')
			->orWhere('dd.protocole like :ds6')
			->setParameter('ds1','%'.$critere.'%')
			->setParameter('ds2','%'.$critere.'%')
			->setParameter('ds3','%'.$critere.'%')
			->setParameter('ds4','%'.$critere.'%')
			->setParameter('ds5','%'.$critere.'%')
			->setParameter('ds6','%'.$critere.'%')
			->getQuery()->getResult();
			$resultats=array_merge($resultats,$resultat);
		}
		
		return $resultats;
	}
}
