<?php

namespace AppBundle\Repository;

/**
 * DetailparametreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetailparametreRepository extends \Doctrine\ORM\EntityRepository
{
}
