<?php

namespace AppBundle\Repository;

/**
 * DispositifRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DispositifRepository extends \Doctrine\ORM\EntityRepository
{
}
