<?php

namespace AppBundle\Repository;

/**
 * EpingleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EpingleRepository extends \Doctrine\ORM\EntityRepository
{
    public function getListepinglesPatient($user){
    $qb = $this->createQueryBuilder('e');
    $qb->select('e');
    $qb->join('e.patient', 'p');
    $qb->where('e.user = :user')
    ->setParameter('user',$user);
    $qb->addSelect('p');
    $query=$qb->getQuery();

    $result=$query->getResult();

    return $result;
    
    }
}
