<?php

namespace AppBundle\Repository;

/**
 * EvolutionprotocoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvolutionprotocoleRepository extends \Doctrine\ORM\EntityRepository
{
}
