<?php

namespace AppBundle\Repository;

/**
 * ExamenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExamenRepository extends \Doctrine\ORM\EntityRepository
{
	public function geExamen($patients){
		$qb = $this->createQueryBuilder('e')		
		->where('e.patient IN (:ds)')	
		->setParameter('ds', $patients);
		
		return $qb->getQuery()->getResult();
	}
	
	
	
	public function getNbExamens(){
	    $qb = $this->createQueryBuilder('e');
	   // $qb->select('p');
	    $query=$qb->getQuery();
	    //$query=$querybuilder->getQuery();
	    $result=$query->getResult();
	    return count($result);
	}
	
	public function getExamensByIdDetailDose($ddid){
	    $qb = $this->createQueryBuilder('e');
	    $qb->innerJoin('e.region', 'r')
	    ->innerJoin('r.regiondose', 'rd')
	    ->innerJoin('rd.dose', 'd')
	    ->innerJoin('d.detail_dose', 'dd')
	    ->where('dd.id IN (:ddid)')
	    ->setParameter('ddid', $ddid);
	    $query=$qb->getQuery();
	    $result=$query->getResult();
	    return $result;
	}
}
