<?php

namespace AppBundle\Repository;

/**
 * FichierdcmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FichierdcmRepository extends \Doctrine\ORM\EntityRepository
{
}
