<?php

namespace AppBundle\Repository;

/**
 * MailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailsRepository extends \Doctrine\ORM\EntityRepository
{
}
