<?php

namespace AppBundle\Repository;

/**
 * MoynrdmodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MoynrdmodRepository extends \Doctrine\ORM\EntityRepository
{
}
