<?php

namespace AppBundle\Repository;

/**
 * MoynrdmodradioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MoynrdmodradioRepository extends \Doctrine\ORM\EntityRepository
{
}
