<?php

namespace AppBundle\Repository;

/**
 * MoynrdmodbyprotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MoynrdmodbyprotoRepository extends \Doctrine\ORM\EntityRepository
{
}
