<?php

namespace AppBundle\Repository;

/**
 * NbNrdByProtoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NbNrdByProtoRepository extends \Doctrine\ORM\EntityRepository
{
}
