<?php

namespace AppBundle\Repository;

/**
 * NoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoteRepository extends \Doctrine\ORM\EntityRepository
{
	
	
	public function getnote($patient){
		$qb = $this->createQueryBuilder('n')
		->innerJoin('n.createur', 'c')
		->addselect('c');
		$qb->where('n.patient = :patientnom')
		->setParameter('patientnom',$patient)
		->orderBy('n.datenote', 'DESC');
		
		
		return $qb->getQuery()->getResult();
		
	}
	
	
	public function getLastnote($patient){
			$qb = $this->createQueryBuilder('n')->
			innerJoin('n.createur', 'c')
			->addselect('c');
			$qb->where('n.patient = :patientnom')
			->setParameter('patientnom',$patient->getId())
			->orderBy('n.datenote', 'DESC')
			->setMaxResults( 1 );
			
			return $qb->getQuery()->getResult();
	}
}
