<?php

namespace AppBundle\Repository;

/**
 * NrdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NrdRepository extends \Doctrine\ORM\EntityRepository
{
}
