<?php

namespace AppBundle\Repository;

/**
 * OptimisationdosedetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OptimisationdosedetailRepository extends \Doctrine\ORM\EntityRepository
{
}
