<?php

namespace AppBundle\Repository;

/**
 * OptimisationdoseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OptimisationdoseRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function getBestComment($optimid){
        $qb = $this->createQueryBuilder('o');
        $qb->select('o');
        $qb->join('o.optimisationdosedetail', 'd');
        $qb->join('d.evaluation', 'e');
        
        $qb->select('o,d,e, MAX(e.valeur) AS maxscore');
        $qb->groupBy('e');
        $qb->where('o.id = :id');
      
        $qb->setFirstResult(0);
        $qb->setParameter('id',$optimid);
        $result= $qb->getQuery()->getResult();
        return $result;
    }
    
    
    public function getNbNotes($optimid){
        $qb = $this->createQueryBuilder('o');
        $qb->select('o');
        $qb->join('o.optimisationdosedetail', 'd');
        $qb->join('d.evaluation', 'e');
        
        $qb->select('count(e.valeur) AS cnt');

        $qb->where('o.id = :id');
        
        $qb->setParameter('id',$optimid);
        $result= $qb->getQuery()->getResult();
       // dump($qb->getQuery());
       // dump($result);
        //die;
        return $result;
    }
}
