<?php

namespace AppBundle\Repository;

/**
 * OrigineEsrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrigineEsrRepository extends \Doctrine\ORM\EntityRepository
{
}
