<?php

namespace AppBundle\Repository;

/**
 * OtlmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OtlmRepository extends \Doctrine\ORM\EntityRepository
{
}
