<?php

namespace AppBundle\Repository;

/**
 * pourcentageNrdByModRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class pourcentageNrdByModRepository extends \Doctrine\ORM\EntityRepository
{
}
