<?php

namespace AppBundle\Repository;

/**
 * PyramideageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PyramideageRepository extends \Doctrine\ORM\EntityRepository
{
}
