<?php

namespace AppBundle\Repository;

/**
 * RegionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegionRepository extends \Doctrine\ORM\EntityRepository
{
	public function getDoses($examen){	
			
		$qb = $this->createQueryBuilder('r');
		$qb->innerJoin('r.examen', 'e')
		->where('r.examen IN (:ds)')
		->setParameter('ds', $examen);
			
		return $qb->getQuery()->getResult();
	}
}
