<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Cache\Region;

/**
 * Region_DoseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Region_DoseRepository extends \Doctrine\ORM\EntityRepository
{
	
		public function getDoses($region){
	
			
			$qb = $this->createQueryBuilder('rd');
			$qb->innerJoin('rd.dose', 'd')
				->innerJoin('rd.region', 'r')
				->where('r IN (:ds)')
				->setParameter('ds', $region)
				->addSelect('d')
			;
			
			return $qb->getQuery()->getResult();
		}

		public function getDosesbymodalite($region,$modalite){
		
				
			$qb = $this->createQueryBuilder('rd');
			$qb->innerJoin('rd.dose', 'd')
			->innerJoin('rd.region', 'r')
			->where('r IN (:ds)')
			->andWhere('d.modalite = :modalite')
			->setParameter('ds', $region)
			->setParameter('modalite', $modalite)
			->addSelect('d')
			;
				
			return $qb->getQuery()->getResult();
		}
}
