<?php

namespace AppBundle\Repository;

/**
 * SalleExamenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalleExamenRepository extends \Doctrine\ORM\EntityRepository
{
}
