<?php

namespace AppBundle\Repository;

/**
 * StatProtocolesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatProtocolesRepository extends \Doctrine\ORM\EntityRepository
{
}
