<?php

namespace AppBundle\Repository;

/**
 * StatistiquesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatistiquesRepository extends \Doctrine\ORM\EntityRepository
{
}
