<?php

namespace AppBundle\Repository;

/**
 * StatsvolumeMoisNRDRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatsvolumeMoisNRDRepository extends \Doctrine\ORM\EntityRepository
{
}
