<?php

namespace AppBundle\Repository;

/**
 * StatsvolumeMoisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatsvolumeMoisRepository extends \Doctrine\ORM\EntityRepository
{
}
