<?php

namespace AppBundle\Repository;

/**
 * TypePersonnalEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypePersonnalEventRepository extends \Doctrine\ORM\EntityRepository
{
}
