<?php

namespace CmsBundle\Admin;

use Sonata\AdminBundle\Datagrid\DatagridMapper;
use Sonata\AdminBundle\Datagrid\ListMapper;
use Sonata\AdminBundle\Form\FormMapper;


class ItemAdmin extends AbstractPostAdmin
{

    protected $parentAssociationMapping = 'collection';


    /**
     * @param DatagridMapper $datagridMapper
     */
    protected function configureDatagridFilters(DatagridMapper $datagridMapper)
    {
        $datagridMapper
            ->add('name', null, ['label' => 'Nom'])
            ->add('published', null, ['label' => 'Publication'])
            ->add('top', null, ['label' => 'Top'])
            ->add('privateAccess', null, array('label' => 'Accès privé'))
            ->add('cache', null, ['label' => 'Cache']);
    }

    /**
     * @param ListMapper $listMapper
     */
    protected function configureListFields(ListMapper $listMapper)
    {
        $listMapper
            ->addIdentifier('cover', null, array('template' => 'CmsBundle:Cms:list_image.html.twig', 'label' => 'Couverture'))
            ->addIdentifier('name', null, ['label' => 'Nom'])
            ->add('published', null, ['label' => 'Publication', 'editable' => true])
            ->add('top', null, ['label' => 'Top', 'editable' => true])
            ->add('privateAccess', null, array('label' => 'Accès privé', 'editable' => true))
            ->add('cache', null, ['label' => 'Cache', 'editable' => true])
            ->add(
                '_action',
                null,
                array(
                    'actions' => array(
                        'edit'   => array(),
                        'delete' => array(),
                        'show'   => ['template' => 'CmsBundle:Post:post_action_show.html.twig']
                    )
                )
            );
    }

    protected function configureFormFields(FormMapper $formMapper)
    {
        $formMapper->add(
            'background',
            'sonata_type_model_list',
            array('required' => false, 'label' => 'Background'),
            array('link_parameters' => array('context' => 'picture', 'provider' => 'sonata.media.provider.image'))
        );
        $formMapper->add('ctaText', null, ['label' => 'Label']);
        $formMapper->add('ctaUrl', null, ['label' => 'URL']);
        $formMapper->add('collection');
        parent::configureFormFields($formMapper); // TODO: Change the autogenerated stub
    }


    public function getTemplate($name)
    {
        switch ($name) {
            case 'edit':
                return 'CmsBundle:Item:item_edit.html.twig';
                break;
            default:
                return parent::getTemplate($name);
                break;
        }
    }
}
