<?php

namespace WorkflowBundle\Repository;

/**
 * WorkflowStepRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkflowStepRepository extends \Doctrine\ORM\EntityRepository
{
    public function getstepbycode($code){
        $qb = $this->createQueryBuilder('s');
        $qb->select('s')
        ->where("replace(upper(a.code),' ','') = :code")
        ->setParameter('code',$code);
        
        return $qb->getQuery()->getSingleResult();
    }
}
