<?php

namespace WorkflowBundle\Repository;

/**
 * WorkflowConditionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkflowConditionRepository extends \Doctrine\ORM\EntityRepository
{
}
