<?php

namespace WorkflowBundle\Repository;

/**
 * WorkflowTransitionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkflowTransitionRepository extends \Doctrine\ORM\EntityRepository
{
}
